server:
  port: 9081

#?????????
#spring:
#  datasource:
#    url: jdbc:mysql://47.94.238.237:3306/depot?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver


spring:
  datasource:
    name: education
    url: jdbc:mysql://47.94.238.237:3306/xiaoyuan
    username: root
    password: 123456
    # ???druid?????
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  typeAliasesPackage: com.education.model
  mapper-locations: classpath:mapping/*.xml, classpath:mapping/base/*.xml

#pagehelper??????
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql